### ISSUE TITLE
Question about missing '/checkpoint/best.pth.tar'

### ISSUE THREAD

**Issue by qiuqicao77** [huguyuehuhu/HCN-pytorch#19]
Hello, can you share your pretrained model '/checkpoint/best.pth.tar'? Thanks!!!!

**Comment by huguyuehuhu** [comment]
The pretrained models are big, you can email me, then I will send them to you through email.

**Comment by ashishhacker** [comment]
I got this error .
2020-02-15 16:09:04,211:WARNING: Setting up a new session...
2020-02-15 16:09:04,222:INFO: Visdom successfully connected to server
2020-02-15 16:09:04,320:WARNING: Setting up a new session...
2020-02-15 16:09:04,328:INFO: Visdom successfully connected to server
2020-02-15 16:09:04,426:WARNING: Setting up a new session...
2020-02-15 16:09:04,434:INFO: Visdom successfully connected to server
2020-02-15 16:09:04,532:WARNING: Setting up a new session...
2020-02-15 16:09:04,542:INFO: Visdom successfully connected to server
2020-02-15 16:09:04,640:WARNING: Setting up a new session...
2020-02-15 16:09:04,649:INFO: Visdom successfully connected to server
2020-02-15 16:09:04,746:INFO: dataset_dir: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/feeder/data2/
2020-02-15 16:09:04,746:INFO: dataset_name: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/experiments/NTU-RGB-D-CV
2020-02-15 16:09:04,746:INFO: model_dir: ./
2020-02-15 16:09:04,747:INFO: model_name: HCN
2020-02-15 16:09:04,747:INFO: load_model: None
2020-02-15 16:09:04,747:INFO: load: True
2020-02-15 16:09:04,747:INFO: mode: test
2020-02-15 16:09:04,747:INFO: num: 03
2020-02-15 16:09:04,747:INFO: model_version: HCN
2020-02-15 16:09:04,747:INFO: experiment_path: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/experiments/NTU-RGB-D-CV/HCN03
2020-02-15 16:09:04,747:INFO: restore_file: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/experiments/NTU-RGB-D-CV/HCN03/checkpoint/best.pth.tar
2020-02-15 16:09:04,747:INFO: gpu_id: 0
2020-02-15 16:09:04,747:INFO: cuda: True
2020-02-15 16:09:04,747:INFO: data_parallel: False
2020-02-15 16:09:04,747:INFO: seed: 0
2020-02-15 16:09:04,748:INFO: lr: 0.001
2020-02-15 16:09:04,748:INFO: lr_decay_type: exp
2020-02-15 16:09:04,748:INFO: lr_step: [100, 160, 200]
2020-02-15 16:09:04,748:INFO: scheduler_gamma: 0.1
2020-02-15 16:09:04,748:INFO: scheduler_gamma2: 0.99
2020-02-15 16:09:04,748:INFO: scheduler_gamma3: 0.5
2020-02-15 16:09:04,748:INFO: patience: 20
2020-02-15 16:09:04,748:INFO: batch_size: 64
2020-02-15 16:09:04,748:INFO: num_epochs: 400
2020-02-15 16:09:04,748:INFO: start_epoch: 0
2020-02-15 16:09:04,748:INFO: save_best_ever_n_epoch: 50
2020-02-15 16:09:04,748:INFO: save_summary_steps: 1
2020-02-15 16:09:04,748:INFO: num_workers: 4
2020-02-15 16:09:04,749:INFO: optimizer: Adam
2020-02-15 16:09:04,749:INFO: weight_decay: 0.0001
2020-02-15 16:09:04,749:INFO: clip: 0.5
2020-02-15 16:09:04,749:INFO: train_feeder_args: {'data_path': None, 'label_path': None, 'random_valid_choose': False, 'random_shift': False, 'random_move': False, 'window_size': 32, 'normalization': False, 'debug': False, 'origin_transfer': 0, 'crop_resize': True, 'p_interval': [0.5, 1]}
2020-02-15 16:09:04,749:INFO: test_feeder_args: {'data_path': None, 'label_path': None, 'random_valid_choose': False, 'random_shift': False, 'random_move': False, 'window_size': 32, 'normalization': False, 'debug': False, 'origin_transfer': 0, 'crop_resize': True, 'p_interval': [0.95]}
2020-02-15 16:09:04,749:INFO: model_args: {'in_channel': 3, 'out_channel': 64, 'window_size': 32, 'num_joint': 25, 'num_person': 2, 'num_class': 60}
2020-02-15 16:09:04,749:INFO: loss_args: {'type': 'CE'}
2020-02-15 16:09:04,749:INFO: dataset_dir: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/feeder/data2/
2020-02-15 16:09:04,749:INFO: dataset_name: /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/experiments/NTU-RGB-D-CV
2020-02-15 16:09:04,749:INFO: mode: test
2020-02-15 16:09:11,672:INFO: HCN(
  (conv1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(1, 1), stride=(1, 1))
    (1): ReLU()
  )
  (conv2): Conv2d(64, 32, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0))
  (conv3): Sequential(
    (0): Conv2d(25, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv4): Sequential(
    (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Dropout2d(p=0.5, inplace=False)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv1m): Sequential(
    (0): Conv2d(3, 64, kernel_size=(1, 1), stride=(1, 1))
    (1): ReLU()
  )
  (conv2m): Conv2d(64, 32, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0))
  (conv3m): Sequential(
    (0): Conv2d(25, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv4m): Sequential(
    (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Dropout2d(p=0.5, inplace=False)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv5): Sequential(
    (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Dropout2d(p=0.5, inplace=False)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv6): Sequential(
    (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Dropout2d(p=0.5, inplace=False)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc7): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): ReLU()
    (2): Dropout2d(p=0.5, inplace=False)
  )
  (fc8): Linear(in_features=512, out_features=60, bias=True)
)
2020-02-15 16:09:11,673:INFO: Loading the datasets...
2020-02-15 16:09:11,892:INFO: - done.
2020-02-15 16:09:11,893:INFO: Restoring parameters from /home/ug2017/cse/17075015/BTP/HCN-pytorch-master/experiments/NTU-RGB-D-CV/HCN03/checkpoint/best.pth.tar
Traceback (most recent call last):
  File "/home/ug2017/cse/17075015/BTP/HCN-pytorch-master/main.py", line 527, in <module>
    loss_fn, metrics, params, args.model_dir,logger, params.restore_file)
  File "/home/ug2017/cse/17075015/BTP/HCN-pytorch-master/main.py", line 382, in test_only
    checkpoint = utils.load_checkpoint(restore_file, model, optimizer)
  File "/home/ug2017/cse/17075015/BTP/HCN-pytorch-master/utils/utils.py", line 172, in load_checkpoint
    raise ("File doesn't exist {}".format(checkpoint))
TypeError: exceptions must derive from BaseException

how can I solve this?
